spring:
  rabbitmq:
    #addresses: 127.0.0.1:5672
    #username: wutongsd
    #password: wutong2017
    addresses: 192.168.3.189:5672
    username: wutong
    password: 111111
    publisher-confirms: true
    virtual-host: /

rabbit: 
  topics: refund_deposit_apply, refund_deposit